language: ruby
rvm:
- 2.2.3
before_script:
- cp config/database.yml.example config/database.yml
- psql -c 'create database "cwiczenie_test";' -U postgres
addons:
  postgresql: '9.3'
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake spec