# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fd47ee786b2aa5f4fabca3c56db9e478bbc2811a1f13ae4b7d7a7e8d9891f71aa5d9f613f819a636632cc18f2b39228edb6f7b532d90b69a65e05c258d9c477

test:
  secret_key_base: 306582890f69f4b2cb6e83b0a918d15f920a694b69da094631f5c06ca938fbc4d5c0e5a18d1fbc58ac2b729f2a9b4123bb9c2a967dbc8ff416703ae1eef148d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
